---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: CentOS-6-x86_64-minimal
    driver_config:
      box: CentOS-6-x86_64-minimal
      box_url: http://mirror.informatik.hs-fulda.de/pub/vagrant/CentOS-6-x86_64-minimal.box
    attributes:
      postgresql:
        enable_pgdg_yum: "true"
suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[postgresql::server] 
      - recipe[opennms::default]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: "7"
      postgresql:
        version: "9.3"
        password:
          postgres: "opennms_pg"
        pg_hba:
          - comment: "#local is for Unix domain socket connections only"
            type: "local"
            db: "all"
            user: "all"
            addr: ""
            method: "ident"
          - comment: "#IPv4 local connections:"
            type: "host"
            db: "all"
            user: "all"
            addr: "127.0.0.1/32"
            method: "md5"
          - comment: "#IPv6 local connections:"
            type: "host"
            db: "all"
            user: "all"
            addr: "::1/128"
            method: "md5"
      opennms:
        release: "stable"
        jpda: "false"
